version: '{build}'

skip_branch_with_pr: true

image: Visual Studio 2022

init:
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,8)

build_script:
  - ps: mkdir ..\app
  - cmd: cd Windows && msbuild.exe mailsync.sln /property:Configuration=Release;Platform=Win32
  - cmd: |
      IF not exist ..\..\app\dist (mkdir ..\..\app\dist)
      XCOPY .\Release\*.* ..\..\app\dist
      COPY "C:\Windows\SysWOW64\msvcr100.dll" ..\..\app\dist\ /Y
      COPY "C:\Windows\SysWOW64\msvcr120.dll" ..\..\app\dist\ /Y
      COPY "C:\Windows\SysWOW64\msvcp100.dll" ..\..\app\dist\ /Y
      COPY "C:\Windows\SysWOW64\msvcp120.dll" ..\..\app\dist\ /Y
      COPY "C:\Windows\SysWOW64\msvcp140.dll" ..\..\app\dist\ /Y
      COPY "C:\Windows\SysWOW64\vcruntime140.dll" ..\..\app\dist\ /Y
      XCOPY /rhy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86" ..\..\app\dist\
  # Validate that the program exits with code 2 (missing arguments). If any DLLs are missing that
  # prevent the application from starting, a code like -1073741515 will be returned.
  - ps: |
      $process = Start-Process -FilePath "..\..\app\dist\mailsync.exe" -PassThru -Wait -NoNewWindow
      $exitCode = $process.ExitCode

      if ($exitCode -ne 2) {
        Write-Host "We expected mailsync.exe to exit with code 2, but we got $exitCode instead."
        exit 1
      } else {
        Write-Host "Exit code was as expected: $exitCode"
      }

before_deploy:
  - ps: (Get-ChildItem -Force -Path ..\..\app).FullName
  - ps: (Get-ChildItem -Force -Path ..\..\app\dist).FullName
  - cmd: 7z -ttar a dummy ..\..\app\dist\*.dll ..\..\app\dist\*.pdb ..\..\app\dist\mailsync.exe -so | 7z -si -tgzip a .\mailsync.tar.gz
  - ps: Get-ChildItem .\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName "win-ia32/$($_.Name)" -DeploymentName s3-deployment }

deploy:
  - provider: S3
    name: s3-deployment
    access_key_id: AKIAJQWOM4SPSY3TXI5Q
    secret_access_key:
      secure: XlLzz7sdvrtgi4g459NvxLfrH/+hOutb+0Osz29unfi4Zcw9N8H8SEaq6m3ZeWc+
    region: us-east-1
    bucket: mailspring-builds
    folder: 'mailsync/$(commit)'
    set_public: true
    # Deploy only when a new tag is created
    on:
      APPVEYOR_REPO_TAG: true

# Stop Appveyor from "Discovering Tests" forever
test: off

environment:
  global:
    encrypted_faf2708e46e2_key:
      secure: mdegN/AldrADhtEop6mDwq6d4jUskzijK2X7Twf2lj9t3jdaW4OtMuJ5Ywyt+GN/N7qMFr7LOvxQ5gz4aoIW+Dg9d03AX3BH1o4BI6g+wdk=
    encrypted_faf2708e46e2_iv:
      secure: B2pwd1AlmQHjIpIau1NylfEMkwJJ5u7NhxgZcU8WicwP6+cmePnAacYIwpe1fXEf
