//
//  MailProcessor.cpp
//  MailSync
//
//  Created by Ben Gotow on 6/20/17.
//  Copyright © 2017 Foundry 376. All rights reserved.
//
//  Use of this file is subject to the terms and conditions defined
//  in 'LICENSE.md', which is part of the Mailspring-Sync package.
//

#include "MailProcessor.hpp"
#include "MailStoreTransaction.hpp"
#include "MailUtils.hpp"
#include "File.hpp"
#include "constants.h"

#include <algorithm>
#include <cctype>

#if defined(_MSC_VER)
#include <direct.h>
#include <codecvt>
#include <locale>
#endif

using namespace std;
using nlohmann::json;

class CleanHTMLBodyRendererTemplateCallback : public Object, public HTMLRendererTemplateCallback {
    mailcore::String * templateForMainHeader(MessageHeader * header) {
        return MCSTR("");
    }

    mailcore::String * templateForAttachment(AbstractPart * part) {
        return MCSTR("");
    }

    mailcore::String * templateForAttachmentSeparator() {
        return MCSTR("");
    }
    
    // Normally this calls through to XMLTidy but we have our own sanitizer at the Javascript
    // level and Tidy has led to some bugs due to its very strict parsing:
    // https://github.com/Foundry376/Mailspring/issues/301#issuecomment-342265351
    mailcore::String * cleanHTMLForPart(mailcore::String * html) {
        return html;
    }

    // TODO: Image attachments can be added to the middle of messages
    // by putting them between two HTML parts and we can render them
    // within the body this way. However the attachments don't have cid's,
    // and the client expects to filter attachments based on whether they
    // have cids.
    
//    mailcore::String * templateForImage(AbstractPart * part) {
//        MailUtils::idForFilePart(part)
//        return MCSTR("<img src=\"{{CONTENTID}}\" data-size=\"{{SIZE}}\" data-filename=\"{{FILENAME}}\" />");
//    }
//
//    bool canPreviewPart(AbstractPart * part) {
//        string t = part->mimeType()->UTF8Characters();
//        
//        if ((t == "image/png") || (t == "image/jpeg") || (t == "image/jpg") || (t == "image/gif")) {
//            return true;
//        }
//        return false;
//    }
};

string stringByAppendingOrSkipping(string input, string val) {
    auto valWithSpace = " " + val;
    if (input.find(valWithSpace) != std::string::npos) {
        return input;
    }
    return input + valWithSpace;
}

MailProcessor::MailProcessor(shared_ptr<Account> account, MailStore * store) :
    store(store),
    account(account),
    logger(spdlog::get("logger"))
{

}

/*
 Ingests one copy of a message reported by a folder scan. Message ids are a hash of the
 headers, so a message already known from another folder or UID is found by id and the
 copy recorded as a placement on it. The lookup comes first so a flag change does not
 start a transaction that is rolled back on every message; the insert can still hit a
 constraint error (SQLite 19) when the other worker ingested the same message a moment
 ago, or the two race on one (folder, UID) of the MessageFolder unique index.
 */
shared_ptr<Message> MailProcessor::insertFallbackToUpdateMessage(IMAPMessage * mMsg, Folder & folder, time_t syncDataTimestamp) {
    Query q = Query().equal("id", MailUtils::idForMessage(folder.accountId(), folder.path(), mMsg));
    auto localMessage = store->find<Message>(q);
    if (localMessage != nullptr) {
        updateMessage(localMessage.get(), mMsg, folder, syncDataTimestamp);
        return localMessage;
    }
    try {
        return insertMessage(mMsg, folder, syncDataTimestamp);
    } catch (const SQLite::Exception & ex) {
        if (ex.getErrorCode() != 19) { // constraint failed
            throw;
        }
        localMessage = store->find<Message>(q);
        if (localMessage.get() == nullptr) {
            throw;
        }
        updateMessage(localMessage.get(), mMsg, folder, syncDataTimestamp);
        return localMessage;
    }
}

shared_ptr<Message> MailProcessor::insertMessage(IMAPMessage * mMsg, Folder & folder, time_t syncDataTimestamp) {
    shared_ptr<Message> msg = make_shared<Message>(mMsg, folder, syncDataTimestamp);
    shared_ptr<Thread> thread = nullptr;

    Array * references = mMsg->header()->references();
    if (references == nullptr) {
        references = new Array();
        references->autorelease();
    }

    {
        MailStoreTransaction transaction{store, "insertMessage"};

        // Find the correct thread

        if (mMsg->gmailThreadID()) {
            Query query = Query().equal("gThrId", to_string(mMsg->gmailThreadID()));
            thread = store->find<Thread>(query);
            
        } else if (!mMsg->header()->isMessageIDAutoGenerated()) {
            // find an existing thread using the references. Note - a rouge client could
            // throw a lot of shit in here, limit the number of refs we look at to 50.
            // TODO: It appears we should technically use the first 1 and then last 49.
            int refcount = min(50, (int)references->count());
            SQLite::Statement tQuery(store->db(), "SELECT Thread.* FROM Thread INNER JOIN ThreadReference ON ThreadReference.threadId = Thread.id WHERE ThreadReference.accountId = ? AND ThreadReference.headerMessageId IN (" + MailUtils::qmarks(1 + refcount) + ") LIMIT 1");
            tQuery.bind(1, msg->accountId());
            tQuery.bind(2, msg->headerMessageId());
            for (int i = 0; i < refcount; i ++) {
                String * ref = (String *)references->objectAtIndex(i);
                // Skip null entries that could arise from malformed reference headers
                if (ref == nullptr) {
                    tQuery.bind(3 + i, "");
                    continue;
                }
                tQuery.bind(3 + i, ref->UTF8Characters());
            }
            if (tQuery.executeStep()) {
                thread = make_shared<Thread>(tQuery);
            }
        }
        
        if (thread == nullptr) {
            // TODO: could move to message save hooks
            thread = make_shared<Thread>(msg->id(), account->id(), msg->subject(), mMsg->gmailThreadID());
        }
        
        msg->setThreadId(thread->id());

        // Written before the Message row so the thread diff below reads the snapshot the helper
        // wrote; an id collision on the insert rolls the row back with the transaction.
        string displaced = store->upsertPlacement(*msg, folder, mMsg->uid(), MessageAttributesForMessage(mMsg));

        // Apply the new message's attributes to the thread (folder/label refcounts,
        // unread/starred counters, timestamps) BEFORE saving the thread. This avoids
        // Message::afterSave re-loading and re-saving the thread a second time.
        MessageSnapshot empty = MessageEmptySnapshot;
        thread->applyMessageAttributeChanges(empty, msg.get(), store);
        msg->captureSnapshot();
        msg->_skipThreadUpdatesAfterSave = true;

        // Index the thread metadata for search. We only do this once and it'd
        // be costly to make it part of the save hooks.
        appendToThreadSearchContent(thread.get(), msg.get(), nullptr);
        store->save(thread.get());
        store->save(msg.get());
        
        // Make the thread accessible by all of the message references
        upsertThreadReferences(thread->id(), thread->accountId(), msg->headerMessageId(), references);

        saveDisplacedMessage(displaced);

        transaction.commit();
    }

    upsertContacts(msg.get());

    return msg;
}

/*
 Records the copy at (folder, uid) on a message that already exists. Only that placement
 is compared against what the server reported. The `syncedAt` guard is message-level:
 while a task the user queued is in flight, a scan of the source folder must not
 resurrect the copy being moved away.
 */
void MailProcessor::updateMessage(Message * local, IMAPMessage * remote, Folder & folder, time_t syncDataTimestamp)
{
    if (local->syncedAt() > syncDataTimestamp) {
        logger->warn("Ignoring changes to {}, local data is newer {} < {}", local->subject(), syncDataTimestamp, local->syncedAt());
        return;
    }
    
    auto updated = MessageAttributesForMessage(remote);

    bool noChanges = false;
    bool known = false;
    for (auto & p : store->placementsForMessage(local->id())) {
        if (p.folderId != folder.id() || p.remoteUID != updated.uid) {
            continue;
        }
        known = true;
        MessageAttributes existing{p.remoteUID, p.unread, p.starred, p.draft, {}};
        for (auto & l : p.labels) {
            existing.labels.push_back(l.get<string>());
        }
        noChanges = p.isLive() && MessageAttributesMatch(existing, updated);
        if (noChanges) {
            break;
        }
        logger->info("- Updating message {} in {}", local->id(), folder.path());
        if (!p.isLive()) {
            logger->info("-- UID {} reappeared", updated.uid);
        }
        if (updated.unread != existing.unread) {
            logger->info("-- Unread ({} to {})", existing.unread, updated.unread);
        }
        if (updated.starred != existing.starred) {
            logger->info("-- Starred ({} to {})", existing.starred, updated.starred);
        }
        if (updated.draft != existing.draft) {
            logger->info("-- Draft ({} to {})", existing.draft, updated.draft);
        }
        if (updated.labels != existing.labels) {
            logger->info("-- XGMLabels ({} to {})", json(existing.labels).dump(), json(updated.labels).dump());
        }
        break;
    }
    if (noChanges) {
        return;
    }
    if (!known) {
        logger->info("- Message {} has a copy in {} (UID {})", local->id(), folder.path(), updated.uid);
    }

    {
        MailStoreTransaction transaction{store, "updateMessage"};

        json before = local->toJSON();
        string displaced = store->upsertPlacement(*local, folder, updated.uid, updated);

        if (account->provider() == "gmail") {
            string role = folder.role();
            if (role == "all" || role == "spam" || role == "trash") {
                store->removePlacementsOutsideFolder(*local, folder.id());
            }
        }

        // Only a change the client can see is worth a persist delta and a thread update; a
        // second copy's flags or a UIDVALIDITY relink may have changed the row alone.
        if (local->toJSON() != before) {
            logger->info("-- Folders now {}", local->folders().dump());
            local->setSyncedAt(syncDataTimestamp);
            store->save(local);
        }

        saveDisplacedMessage(displaced);

        transaction.commit();
    }
}

// A (folder, UID) row taken over from another message leaves that message's snapshot
// listing a copy it no longer has.
void MailProcessor::saveDisplacedMessage(const string & messageId) {
    if (messageId.empty()) {
        return;
    }
    auto displaced = store->find<Message>(Query().equal("id", messageId));
    if (displaced == nullptr) {
        return;
    }
    logger->warn("- Message {} lost a placement to another message at the same UID", messageId);
    store->refreshMessageFromPlacements(*displaced);
    store->save(displaced.get());
}

namespace {

// Lowercase + trim ASCII whitespace. Uses unsigned-char lambdas because
// the C ctype functions are UB on negative `char` values, and these headers
// can carry arbitrary bytes from the public Internet.
std::string lowerTrimmed(const std::string & s) {
    auto isWs = [](unsigned char c) { return std::isspace(c) != 0; };
    auto first = std::find_if_not(s.begin(), s.end(), isWs);
    auto last  = std::find_if_not(s.rbegin(), s.rend(), isWs).base();
    if (first >= last) return {};
    std::string out(first, last);
    std::transform(out.begin(), out.end(), out.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return out;
}

// Classify an Importance / X-MSMail-Priority value to one of
// "high" / "low" / "normal", or empty if unrecognized. Token-based to avoid
// substring false positives like "abnormal" matching "normal" or
// "highly recommended" matching "high".
std::string classifyImportanceText(const std::string & raw) {
    std::string v = lowerTrimmed(raw);
    if (v.empty()) return {};
    // Outlook/MAPI extended values that some gateways pass through verbatim.
    if (v.compare(0, 12, "above normal") == 0) return "high";
    if (v.compare(0, 12, "below normal") == 0) return "low";
    // Otherwise compare the first whitespace/comment-delimited token.
    auto cut = v.find_first_of(" \t(,;");
    std::string token = (cut == std::string::npos) ? v : v.substr(0, cut);
    if (token == "high")   return "high";
    if (token == "low")    return "low";
    if (token == "normal") return "normal";
    return {};
}

// X-Priority: numeric scale 1-5 per RFC 2076. Other digits and non-digit
// values are treated as unrecognized so the caller can fall through.
std::string classifyXPriority(const std::string & raw) {
    std::string v = lowerTrimmed(raw);
    if (v.empty() || !std::isdigit(static_cast<unsigned char>(v[0]))) return {};
    switch (v[0]) {
        case '1': case '2': return "high";
        case '3':           return "normal";
        case '4': case '5': return "low";
        default:            return {};
    }
}

} // namespace

void MailProcessor::retrievedMessageBody(Message * message, MessageParser * parser) {
    CleanHTMLBodyRendererTemplateCallback * htmlCallback = new CleanHTMLBodyRendererTemplateCallback();
    const char * bodyRepresentation;
    bool bodyIsPlaintext;
    
    Array * partAttachments = Array::array();
    Array * htmlInlineAttachments = Array::array();

    // Note - exposed this lower level API manually so that we can avoid running this renderer three
    // times to retrieve attachments, relatedAttachments, message HTML separately. The code seems to build
    // and discard things you don't ask for.
    String * html = parser->htmlRenderingAndAttachments(htmlCallback, partAttachments, htmlInlineAttachments);
    if (html == NULL) {
        logger->warn("Failed to render message body for message {}: parser returned null", message->id());
        MC_SAFE_RELEASE(htmlCallback);
        return;
    }
    String * text = html;

    if (html->hasPrefix(MCSTR("PLAINTEXT:"))) {
        text = html->substringFromIndex(10);
        bodyRepresentation = text->UTF8Characters();
        bodyIsPlaintext = true;
    } else {
        String * flattenedHTML = html->flattenHTML();
        if (flattenedHTML != NULL) {
            text = flattenedHTML->stripWhitespace();
        } else {
            // flattenHTML failed, use empty string to avoid crash
            text = MCSTR("");
        }
        bodyRepresentation = html->UTF8Characters();
        bodyIsPlaintext = false;
    }
    MC_SAFE_RELEASE(htmlCallback);

    // build file containers for the attachments and write them to disk
    Array attachments = Array();
    attachments.addObjectsFromArray(partAttachments);
    attachments.addObjectsFromArray(htmlInlineAttachments);
    
    vector<File> files;
    for (int ii = 0; ii < attachments.count(); ii ++) {
        Attachment * a = (Attachment *)attachments.objectAtIndex(ii);
        if (a->contentID() && a->isInlineAttachment() == false) {
            // This is suspicious - the item has a content ID but we don't think it's an attachment?
            // Look in the content of the message for "cid:XXX". If we find it, the MIME was missing
            // the Content-Disposition but the client should render it inline.
            if (html->locationOfString(MCSTR("cid:")->stringByAppendingString(a->contentID())) != -1) {
                a->setInlineAttachment(true);
            }
        }
        
        File f = File(message, a);
        
        bool duplicate = false;
        for (auto & other : files) {
            if (other.partId() == string(a->partID()->UTF8Characters())) {
                duplicate = true;
                logger->info("Attachment is duplicate: {}", f.toJSON().dump());
                break;
            }
        }
        
        // Sometimes the HTML will reference "cid:filename.png@123123garbage" and the file will
        // not have a contentId. The client does not support this, so if cid:filename.png appears
        // in the body we manually make it the contentId
        if (f.contentId().is_null() && strstr(bodyRepresentation, ("cid:" + f.filename()).c_str()) != nullptr) {
            f.setContentId(f.filename());
        }

        if (!duplicate) {
            if (!retrievedFileData(&f, a->data())) {
                logger->info("Could not save file data!");
            }
            files.push_back(f);
        }
    }
    
    // enter transaction
    {
        MailStoreTransaction transaction{store, "retrievedMessageBody"};

        // The caller's object predates the body fetch - up to 30 fetches, on the other
        // worker's schedule - and the message's placements or flags may have changed since.
        // Saving it would write that stale folders snapshot and unread state over the row,
        // and no scan repairs the snapshot: scans compare MessageFolder against the server.
        auto fresh = store->find<Message>(Query().equal("id", message->id()));
        if (fresh == nullptr) {
            logger->info("Message {} was removed while its body was fetched, discarding the body.", message->id());
            return;
        }
        message = fresh.get();
        
        // write body to the MessageBodies table
        SQLite::Statement insert(store->db(), "REPLACE INTO MessageBody (id, value, fetchedAt) VALUES (?, ?, datetime('now'))");
        insert.bind(1, message->id());
        insert.bind(2, bodyRepresentation);
        insert.exec();
        
        // write files to the files table
        
        // try to save the files to the database. We don't care about failures here -
        // it's possible the files are already there if we're re-fetching this message
        // for some reason and we haven't loaded the existing ones.
        for (auto & file : files) {
            try {
                store->save(&file);
            } catch (SQLite::Exception &) {
                logger->warn("Unable to insert file ID {} - it must already exist.", file.id());
            }
        }
        
        // append the body text to the thread's FTS5 search index
        auto thread = store->find<Thread>(Query().equal("id", message->threadId()));
        if (thread.get() != nullptr) {
            appendToThreadSearchContent(thread.get(), nullptr, text);
        }

        // write the message snippet. This also gives us the database trigger!
        message->setSnippet(text->substringToIndex(400)->UTF8Characters());
        message->setPlaintext(bodyIsPlaintext);
        message->setBodyForDispatch(bodyRepresentation);
        message->setFiles(files);

        // extract additional headers from the full message that weren't available
        // during initial sync (which only fetches IMAP ENVELOPE)
        MessageHeader * msgHeader = parser->header();
        if (msgHeader != nullptr) {
            String * listUnsub = msgHeader->extraHeaderValueForName(MCSTR("List-Unsubscribe"));
            String * listUnsubPost = msgHeader->extraHeaderValueForName(MCSTR("List-Unsubscribe-Post"));

            if (listUnsub != nullptr) {
                message->_data["hListUnsub"] = listUnsub->UTF8Characters();
            }
            if (listUnsubPost != nullptr) {
                message->_data["hListUnsubPost"] = listUnsubPost->UTF8Characters();
            }

            // Resolve message importance to a canonical "high" / "low" / "normal".
            // Precedence: Importance > X-Priority > X-MSMail-Priority. The Importance
            // header is authoritative when present — if its value is unrecognized we
            // stop the chain rather than fall through to lower-precedence headers
            // that might contradict an explicitly-set Importance.
            string importance;
            if (String * h = msgHeader->extraHeaderValueForName(MCSTR("Importance"))) {
                importance = classifyImportanceText(h->UTF8Characters());
            } else {
                if (String * h = msgHeader->extraHeaderValueForName(MCSTR("X-Priority"))) {
                    importance = classifyXPriority(h->UTF8Characters());
                }
                if (importance.empty()) {
                    if (String * h = msgHeader->extraHeaderValueForName(MCSTR("X-MSMail-Priority"))) {
                        importance = classifyImportanceText(h->UTF8Characters());
                    }
                }
            }
            if (!importance.empty()) {
                message->_data["hImportance"] = importance;
            }
        }

        store->save(message);
        
        transaction.commit();
    }
}


bool MailProcessor::retrievedFileData(File * file, Data * data) {
    string root = MailUtils::getEnvUTF8("CONFIG_DIR_PATH") + FS_PATH_SEP + "files";
    string path = MailUtils::pathForFile(root, file, true);
#ifdef _MSC_VER
    wstring_convert<codecvt_utf8<wchar_t>, wchar_t> convert;
    return (data->writeToFile(AS_WIDE_MCSTR(convert.from_bytes(path))) == ErrorNone);
#else
    return (data->writeToFile(AS_MCSTR(path)) == ErrorNone);
#endif
}

void MailProcessor::tombstonePlacements(Folder & folder, const vector<uint32_t> & uids)
{
    logger->info("Tombstoning {} UIDs no longer present in {}.", uids.size(), folder.path());
    vector<string> affected;
    {
        MailStoreTransaction transaction{store, "tombstonePlacements"};
        affected = store->tombstonePlacements(folder, uids, time(0));
        transaction.commit();
    }
    saveMessagesAfterPlacementChange(affected);
}

void MailProcessor::tombstonePlacements(Folder & folder, Query & uidQuery)
{
    logger->info("Tombstoning UIDs matching {} no longer present in {}.", uidQuery.getSQL(), folder.path());
    vector<string> affected;
    {
        MailStoreTransaction transaction{store, "tombstonePlacements"};
        affected = store->tombstonePlacements(folder, uidQuery, time(0));
        transaction.commit();
    }
    saveMessagesAfterPlacementChange(affected);
}

void MailProcessor::tombstoneUnassignedPlacements(Folder & folder)
{
    vector<string> affected;
    {
        MailStoreTransaction transaction{store, "tombstoneUnassignedPlacements"};
        affected = store->tombstoneUnassignedPlacements(folder, time(0));
        transaction.commit();
    }
    if (affected.size() > 0) {
        logger->info("Tombstoned {} copies in {} the UIDVALIDITY rebuild did not find.", affected.size(), folder.path());
    }
    saveMessagesAfterPlacementChange(affected);
}

/*
 Catches each message's snapshot up with its rows after a bulk helper changed them, in
 transactions of 100 so a mass deletion does not hold the database for the whole batch.
 A message left with no rows goes through store->remove so Message::afterRemove balances
 the thread and deletes the body and metadata; the check runs inside the chunk's
 transaction so a copy the other worker records meanwhile keeps its message. A message
 whose snapshot did not change is not saved, so the client gets no persist for a version
 bump alone.
 */
void MailProcessor::saveMessagesAfterPlacementChange(const vector<string> & messageIds)
{
    if (messageIds.empty()) {
        return;
    }
    bool logSubjects = messageIds.size() < 20;
    vector<string> ids = messageIds;
    for (auto chunk : MailUtils::chunksOfVector(ids, 100)) {
        MailStoreTransaction transaction{store, "saveMessagesAfterPlacementChange"};
        refreshMessagesInOpenTransaction(chunk, logSubjects);
        transaction.commit();
    }
}

// The caller owns the transaction so a bulk row change and the messages it affects can be
// committed together.
void MailProcessor::refreshMessagesInOpenTransaction(const vector<string> & messageIds, bool logSubjects)
{
    vector<string> ids = messageIds;
    auto messages = store->findAll<Message>(Query().equal("id", ids));
    for (auto & msg : messages) {
        if (store->placementsForMessage(msg->id()).empty()) {
            if (logSubjects) {
                logger->info("-- Removing \"{}\" ({}), no remaining copies", msg->subject(), msg->id());
            }
            store->remove(msg.get());
            continue;
        }
        json before = msg->toJSON();
        store->refreshMessageFromPlacements(*msg);
        if (msg->toJSON() == before) {
            continue;
        }
        if (logSubjects) {
            logger->info("-- \"{}\" ({}) now in {}", msg->subject(), msg->id(), msg->folders().dump());
        }
        store->save(msg.get());
    }
}

/*
 End-of-pass sweep. A tombstone older than the start of the pass has had every folder
 scanned since it was written, so a copy that moved elsewhere has already been recorded
 and cleared it (MailStore::upsertPlacement). What is left is dropped and the messages
 that held it saved or removed. The save matters even when copies remain: derived
 unread/starred are OR'd over tombstones, so a message whose only unread copy was
 deleted elsewhere reads as unread until the tombstone is gone.

 Each chunk deletes its rows and repairs its messages in one transaction. Deleting every
 tombstone first and repairing afterwards would leave a window - the whole chunked loop,
 seconds when a large trash is emptied - in which a quit or a crash strands messages with
 no MessageFolder row and a stale, non-empty snapshot. Nothing would ever revisit them:
 the tombstones that named them are gone, and folder scans only produce ids through
 MessageFolder.
 */
void MailProcessor::sweepExpiredTombstones(time_t before)
{
    vector<string> candidates = store->expiredTombstoneMessageIds(account->id(), before);
    if (candidates.empty()) {
        return;
    }
    logger->info("Sync loop sweeping expired tombstones from {} messages.", candidates.size());
    bool logSubjects = candidates.size() < 20;
    for (auto chunk : MailUtils::chunksOfVector(candidates, 100)) {
        MailStoreTransaction transaction{store, "sweepExpiredTombstones"};
        store->deleteExpiredTombstones(account->id(), before, chunk);
        refreshMessagesInOpenTransaction(chunk, logSubjects);
        transaction.commit();
    }
}

void MailProcessor::appendToThreadSearchContent(Thread * thread, Message * messageToAppendOrNull, String * bodyToAppendOrNull) {
    string to = "";
    string from = "";
    string categories = thread->categoriesSearchString();
    string body = "";
    
    // retrieve the current index if there is one
    if (thread->searchRowId()) {
        SQLite::Statement existing(store->db(), "SELECT to_, from_, body FROM ThreadSearch WHERE rowid = ?");
        existing.bind(1, (double)thread->searchRowId());
        if (existing.executeStep()) {
            to = existing.getColumn("to_").getString();
            from = existing.getColumn("from_").getString();
            body = existing.getColumn("body").getString();
        }
    }
    
    if (messageToAppendOrNull != nullptr) {
        for (auto c : messageToAppendOrNull->to()) {
            if (c.count("email")) { to = stringByAppendingOrSkipping(to, c["email"].get<string>()); }
            if (c.count("name")) { to = stringByAppendingOrSkipping(to, c["name"].get<string>()); }
        }
        for (auto c : messageToAppendOrNull->cc()) {
            if (c.count("email")) { to = stringByAppendingOrSkipping(to, c["email"].get<string>()); }
            if (c.count("name")) { to = stringByAppendingOrSkipping(to, c["name"].get<string>()); }
        }
        for (auto c : messageToAppendOrNull->bcc()) {
            if (c.count("email")) { to = stringByAppendingOrSkipping(to, c["email"].get<string>()); }
            if (c.count("name")) { to = stringByAppendingOrSkipping(to, c["name"].get<string>()); }
        }
        for (auto c : messageToAppendOrNull->from()) {
            if (c.count("email")) { from = stringByAppendingOrSkipping(from, c["email"].get<string>()); }
            if (c.count("name")) { from = stringByAppendingOrSkipping(from, c["name"].get<string>()); }
        }
    }
    
    if (bodyToAppendOrNull != nullptr) {
        body = body + " " + bodyToAppendOrNull->substringToIndex(5000)->UTF8Characters();
    }
    
    if (thread->searchRowId()) {
        SQLite::Statement update(store->db(), "UPDATE ThreadSearch SET to_ = ?, from_ = ?, body = ?, categories = ? WHERE rowid = ?");
        update.bind(1, to);
        update.bind(2, from);
        update.bind(3, body);
        update.bind(4, categories);
        update.bind(5, (double)thread->searchRowId());
        update.exec();
    } else {
        SQLite::Statement insert(store->db(), "INSERT INTO ThreadSearch (subject, to_, from_, body, categories, content_id) VALUES (?, ?, ?, ?, ?, ?)");
        insert.bind(1, thread->subject());
        insert.bind(2, to);
        insert.bind(3, from);
        insert.bind(4, body);
        insert.bind(5, categories);
        insert.bind(6, thread->id());
        insert.exec();
        thread->setSearchRowId(store->db().getLastInsertRowid());
    }
}

void MailProcessor::upsertThreadReferences(string threadId, string accountId, string headerMessageId, Array * references) {
    SQLite::Statement query(store->db(), "INSERT OR IGNORE INTO ThreadReference (threadId, accountId, headerMessageId) VALUES (?,?,?)");
    query.bind(1, threadId);
    query.bind(2, accountId);
    query.bind(3, headerMessageId);
    query.exec();
    query.reset();

    // Index the first reference (thread root) and last N-1 references (most recent).
    // This ensures thread continuity through the root while keeping recent messages connected.
    // If count <= MAX_REFS, all references are indexed.
    const int MAX_REFS = 100;
    int count = (int)references->count();
    int lastNCount = min(MAX_REFS - 1, count - 1);
    int lastNStart = count - lastNCount;

    // Index first reference (thread root)
    if (count > 0) {
        String * firstRef = (String*)references->objectAtIndex(0);
        query.bind(3, firstRef->UTF8Characters());
        query.exec();
        query.reset(); // does not clear bindings 1 and 2! https://sqlite.org/c3ref/reset.html
    }

    // Index last N-1 references (most recent), skipping index 0 to avoid duplicate
    for (int i = max(1, lastNStart); i < count; i++) {
        String * address = (String*)references->objectAtIndex(i);
        // Skip null entries that could arise from malformed reference headers
        if (address == nullptr) {
            continue;
        }
        query.bind(3, address->UTF8Characters());
        query.exec();
        query.reset();
    }
}

void MailProcessor::upsertContacts(Message * message) {
    // As of Mailspring 1.7, we no longer keep around Contacts that you've never
    // sent email to. We actually never really did anything with these.
    if (!message->isSentByUser(store)) {
        return;
    }
    
    map<string, json> byEmail{};
    for (auto & c : message->to()) {
        if (c.count("email")) {
            byEmail[MailUtils::contactKeyForEmail(c["email"].get<string>())] = c;
        }
    }
    for (auto & c : message->cc()) {
        if (c.count("email")) {
            byEmail[MailUtils::contactKeyForEmail(c["email"].get<string>())] = c;
        }
    }
    for (auto & c : message->from()) {
        if (c.count("email")) {
            byEmail[MailUtils::contactKeyForEmail(c["email"].get<string>())] = c;
        }
    }
    
    // contactKeyForEmail returns "" for some emails. Toss out that item
    if (byEmail.count("")) {
        byEmail.erase("");
    }
    
    vector<string> emails{};
    for (auto const& imap: byEmail) {
        emails.push_back(imap.first);
    }
    
    if (emails.size() > 25) {
        // I think it's safe to say mass emails shouldn't create contacts.
        return;
    }
    
    {
        // Index contacts for autocomplete. We do this separately in a transaction that does not
        // emit any deltas, since the client doesn't need to be bothered with contacts changes.
        MailStoreTransaction transaction{store, "insertMessage:contacts"};

        Query query = Query().equal("email", emails).equal("source", CONTACT_SOURCE_MAIL);
        auto results = store->findAll<Contact>(query);
        
        // update refcounts of existing items if this is a sent message
        for (auto & result : results) {
            if (result->refs() < CONTACT_MAX_REFS) {
                result->incrementRefs();
                store->save(result.get());
            }
            byEmail.erase(result->email());
        }
        
        // insert remaining items (contacts not yet in the database)
        for (auto & result : byEmail) {
            string name = result.second.count("name") ? result.second["name"].get<string>() : "";
            string email = result.second.count("email") ? result.second["email"].get<string>() : "";

            // "Mailspring Team" is used in the welcome email sent from the user's own address.
            // Skip creating the contact to avoid saving the wrong display name.
            if (name == "Mailspring Team" && email.find("@getmailspring.com") == string::npos) {
                continue;
            }

            auto c = make_shared<Contact>(result.first, message->accountId(), result.first, 0, CONTACT_SOURCE_MAIL);
            c->setName(name);
            c->incrementRefs();
            store->save(c.get());
        }
        
        store->unsafeEraseTransactionDeltas();
        transaction.commit();
    }
}

